[RPC Framework] Use _script_module_reducer for both ScriptModule and RecursiveScriptModule unconditionally in RPC pickler
Pull Request resolved: https://github.com/pytorch/pytorch/pull/58020

Previously there is no RPC pickler for `RecursiveScriptModule`. Although it is a subclass of `ScriptModule`, the reducer of `ScriptModule` is not triggered for `RecursiveScriptModule`.

TODO: This still cannot fix `test_send_remote_module_over_the_wire_script`, because the pickling of an RRef is involved, but its RPC pickler is not  called.


If the test `test_send_remote_module_over_the_wire_script` is re-enabled:
```
======================================================================
ERROR: test_send_remote_module_over_the_wire_script (test_process_group_agent.ProcessGroupThreeWorkersRemoteModuleTestWithSpawn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/common_distributed.py", line 509, in run_test
    getattr(self, test_name)()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/common_distributed.py", line 393, in wrapper
    fn()
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/dist_utils.py", line 100, in new_test_method
    return_value = old_test_method(self, *arg, **kwargs)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/testing/_internal/distributed/nn/api/remote_module_test.py", line 523, in test_send_remote_module_over_the_wire_script
    attrs = rpc.rpc_sync(
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/distributed/rpc/api.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/distributed/rpc/api.py", line 733, in rpc_sync
    fut = _invoke_rpc(to, func, RPCExecMode.SYNC, args, kwargs, timeout)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/distributed/rpc/api.py", line 643, in _invoke_rpc
    (pickled_python_udf, tensors) = _default_pickler.serialize(
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/distributed/rpc/internal.py", line 199, in serialize
    p.dump(obj)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/distributed/rpc/internal.py", line 109, in _recursive_script_module_reducer
    torch.jit.save(recursive_script_module, f)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/jit/_serialization.py", line 83, in save
    ret = m.save_to_buffer(_extra_files=_extra_files)
  File "/data/users/wayi/fbsource/fbcode/buck-out/dev/gen/caffe2/test/distributed/rpc/process_group_agent#binary,link-tree/torch/jit/_script.py", line 580, in save_to_buffer
    return self._c.save_to_buffer(*args, **kwargs)
RuntimeError: RRef jit pickling is only allowed inside RPC calls.
```
ghstack-source-id: 128903238

Differential Revision: [D28346758](https://our.internmc.facebook.com/intern/diff/D28346758/)